[tool.ruff]
line-length = 100

# Enable
select = [
    "E", # pycodestyle
    "F", # flake8
    "B", # flake8-bugbear
    "I", # Isort
    "PL", # Pylint
    "PLC", # Pylint Convention
    "PLE", # Pylint Error
    "PLR", # Pylint Refactor
    "PLW", # Pylint Warning
    "W",  # pycodestyle
    "UP", # pyupgrade
    "YTT", # flake8-2020
    "S", # flake8-bandit
    "FBT", # flake8-boolean-trap
    "C4", # flake8-comprehensions
    "ICN", # flake8-import-conventions
    "PIE", # flake8-pie
    "Q", # flake8-quotes
    "SIM", # flake8-simplify
    "TID", # flake8-tidy-imports
    "ARG", # flake8-unused-arguments
    "PTH"# flake8-use-pathlib
]

ignore = [
    "PLR0913" # too-many-arguments
]

[tool.black]
line-length = 100
