[tool.ruff]
line-length = 100

# Enable
# flake8-bugbear (`B`),
# Isort (I)
# Pylint(PL, PLC, PLE, PLR, PLW),
# pycodestyle(E, W)
# pyupgrade (UP)
# flake8-2020 (YTT)
# flake8-bandit (S)
# flake8-boolean-trap (FBT)
# flake8-comprehensions (C4)
# flake8-import-conventions (ICN)
# flake8-pie (PIE)
# flake8-quotes (Q)
# flake8-simplify (SIM)
# flake8-tidy-imports (TID)
# flake8-unused-arguments (ARG)
# flake8-use-pathlib (PTH)
select = ["E", "F", "B", "I", "PL", "PLC", "PLE", "PLR", "PLW", "W", "UP", "YTT", "S", "FBT", "C4", "ICN", "PIE", "Q", "SIM", "TID", "ARG", "PTH"]

# Never enforce `E501` (line length violations).
ignore = ["PLR0913"]

[tool.black]
line-length = 100
